CVP_CONFIGLETS:
  AVD_leaf1-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf1-DC1\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf2-DC1_Po1\n \
    \  no shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ DC1_SPINES_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel6\n   description\
    \ host1-DC1_connected to host1-DC1\n   no shutdown\n   switchport\n   switchport\
    \ access vlan 10\n   mlag 6\n   spanning-tree portfast\n!\ninterface Ethernet1\n\
    \   description MLAG_PEER_leaf2-DC1_Ethernet1\n   no shutdown\n   channel-group\
    \ 1 mode active\n!\ninterface Ethernet2\n   description SPINE1-DC1_Ethernet2\n\
    \   no shutdown\n   channel-group 2 mode active\n!\ninterface Ethernet3\n   description\
    \ SPINE2-DC1_Ethernet2\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet6\n   description host1-DC1\n   no shutdown\n   channel-group 6 mode\
    \ active\n!\ninterface Ethernet7\n   description host1-DC1\n   no shutdown\n \
    \  channel-group 6 mode active\n!\ninterface Vlan4094\n   description MLAG_PEER\n\
    \   no shutdown\n   mtu 1500\n   no autostate\n   ip address 192.168.0.0/31\n\
    !\nip routing\nno ip routing vrf MGMT\n!\nmlag configuration\n   domain-id mlag1\n\
    \   local-interface Vlan4094\n   peer-address 192.168.0.1\n   peer-link Port-Channel1\n\
    \   reload-delay mlag 300\n   reload-delay non-mlag 330\n!\nmanagement api http-commands\n\
    \   protocol https\n   no shutdown\n   !\n   vrf MGMT\n      no shutdown\n!\n\
    end\n"
  AVD_leaf2-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf2-DC1\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf1-DC1_Po1\n \
    \  no shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ DC1_SPINES_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel6\n   description\
    \ host1-DC1_connected to host1-DC1\n   no shutdown\n   switchport\n   switchport\
    \ access vlan 10\n   mlag 6\n   spanning-tree portfast\n!\ninterface Ethernet1\n\
    \   description MLAG_PEER_leaf1-DC1_Ethernet1\n   no shutdown\n   channel-group\
    \ 1 mode active\n!\ninterface Ethernet2\n   description SPINE1-DC1_Ethernet3\n\
    \   no shutdown\n   channel-group 2 mode active\n!\ninterface Ethernet3\n   description\
    \ SPINE2-DC1_Ethernet3\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet6\n   description host1-DC1\n   no shutdown\n   channel-group 6 mode\
    \ active\n!\ninterface Ethernet7\n   description host1-DC1\n   no shutdown\n \
    \  channel-group 6 mode active\n!\ninterface Vlan4094\n   description MLAG_PEER\n\
    \   no shutdown\n   mtu 1500\n   no autostate\n   ip address 192.168.0.1/31\n\
    !\nip routing\nno ip routing vrf MGMT\n!\nmlag configuration\n   domain-id mlag1\n\
    \   local-interface Vlan4094\n   peer-address 192.168.0.0\n   peer-link Port-Channel1\n\
    \   reload-delay mlag 300\n   reload-delay non-mlag 330\n!\nmanagement api http-commands\n\
    \   protocol https\n   no shutdown\n   !\n   vrf MGMT\n      no shutdown\n!\n\
    end\n"
  AVD_leaf3-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf3-DC1\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf4-DC1_Po1\n \
    \  no shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ DC1_SPINES_Po4\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel6\n   description\
    \ host2-DC1_connected to host2-DC1\n   no shutdown\n   switchport\n   switchport\
    \ access vlan 10\n   mlag 6\n   spanning-tree portfast\n!\ninterface Ethernet1\n\
    \   description MLAG_PEER_leaf4-DC1_Ethernet1\n   no shutdown\n   channel-group\
    \ 1 mode active\n!\ninterface Ethernet2\n   description SPINE1-DC1_Ethernet4\n\
    \   no shutdown\n   channel-group 2 mode active\n!\ninterface Ethernet3\n   description\
    \ SPINE2-DC1_Ethernet4\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet6\n   description host2-DC1\n   no shutdown\n   channel-group 6 mode\
    \ active\n!\ninterface Ethernet7\n   description host2-DC1\n   no shutdown\n \
    \  channel-group 6 mode active\n!\ninterface Vlan4094\n   description MLAG_PEER\n\
    \   no shutdown\n   mtu 1500\n   no autostate\n   ip address 192.168.0.4/31\n\
    !\nip routing\nno ip routing vrf MGMT\n!\nmlag configuration\n   domain-id mlag2\n\
    \   local-interface Vlan4094\n   peer-address 192.168.0.5\n   peer-link Port-Channel1\n\
    \   reload-delay mlag 300\n   reload-delay non-mlag 330\n!\nmanagement api http-commands\n\
    \   protocol https\n   no shutdown\n   !\n   vrf MGMT\n      no shutdown\n!\n\
    end\n"
  AVD_leaf4-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending range\
    \ 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing protocols\
    \ model multi-agent\n!\nhostname leaf4-DC1\n!\nspanning-tree mode mstp\nno spanning-tree\
    \ vlan-id 4094\nspanning-tree mst 0 priority 16384\n!\nno enable password\nno\
    \ aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n!\nvrf instance\
    \ MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_leaf3-DC1_Po1\n \
    \  no shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ DC1_SPINES_Po4\n   no shutdown\n   switchport\n   switchport trunk allowed vlan\
    \ none\n   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel6\n   description\
    \ host2-DC1_connected to host2-DC1\n   no shutdown\n   switchport\n   switchport\
    \ access vlan 10\n   mlag 6\n   spanning-tree portfast\n!\ninterface Ethernet1\n\
    \   description MLAG_PEER_leaf3-DC1_Ethernet1\n   no shutdown\n   channel-group\
    \ 1 mode active\n!\ninterface Ethernet2\n   description SPINE1-DC1_Ethernet5\n\
    \   no shutdown\n   channel-group 2 mode active\n!\ninterface Ethernet3\n   description\
    \ SPINE2-DC1_Ethernet5\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet6\n   description host2-DC1\n   no shutdown\n   channel-group 6 mode\
    \ active\n!\ninterface Ethernet7\n   description host2-DC1\n   no shutdown\n \
    \  channel-group 6 mode active\n!\ninterface Vlan4094\n   description MLAG_PEER\n\
    \   no shutdown\n   mtu 1500\n   no autostate\n   ip address 192.168.0.5/31\n\
    !\nip routing\nno ip routing vrf MGMT\n!\nmlag configuration\n   domain-id mlag2\n\
    \   local-interface Vlan4094\n   peer-address 192.168.0.4\n   peer-link Port-Channel1\n\
    \   reload-delay mlag 300\n   reload-delay non-mlag 330\n!\nmanagement api http-commands\n\
    \   protocol https\n   no shutdown\n   !\n   vrf MGMT\n      no shutdown\n!\n\
    end\n"
  AVD_spine1-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending\
    \ range 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing\
    \ protocols model multi-agent\n!\nhostname spine1-DC1\n!\nspanning-tree mode mstp\n\
    no spanning-tree vlan-id 4094\nspanning-tree mst 0 priority 4096\n!\nno enable\
    \ password\nno aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n\
    !\nvrf instance MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_spine2-DC1_Po1\n\
    \   no shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ MLAG1_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel4\n   description\
    \ MLAG2_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 4\n!\ninterface Ethernet1\n   description MLAG_PEER_spine2-DC1_Ethernet1\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ LEAF1-DC1_Ethernet2\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet3\n   description LEAF2-DC1_Ethernet2\n   no shutdown\n   channel-group\
    \ 2 mode active\n!\ninterface Ethernet4\n   description LEAF3-DC1_Ethernet2\n\
    \   no shutdown\n   channel-group 4 mode active\n!\ninterface Ethernet5\n   description\
    \ LEAF4-DC1_Ethernet2\n   no shutdown\n   channel-group 4 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.0.0/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id DC1_SPINES\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.0.1\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
  AVD_spine2-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending\
    \ range 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing\
    \ protocols model multi-agent\n!\nhostname spine2-DC1\n!\nspanning-tree mode mstp\n\
    no spanning-tree vlan-id 4094\nspanning-tree mst 0 priority 4096\n!\nno enable\
    \ password\nno aaa root\n!\nvlan 4094\n   name MLAG_PEER\n   trunk group MLAG\n\
    !\nvrf instance MGMT\n!\ninterface Port-Channel1\n   description MLAG_PEER_spine1-DC1_Po1\n\
    \   no shutdown\n   switchport\n   switchport trunk allowed vlan 2-4094\n   switchport\
    \ mode trunk\n   switchport trunk group MLAG\n!\ninterface Port-Channel2\n   description\
    \ MLAG1_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 2\n!\ninterface Port-Channel4\n   description\
    \ MLAG2_Po2\n   no shutdown\n   switchport\n   switchport trunk allowed vlan none\n\
    \   switchport mode trunk\n   mlag 4\n!\ninterface Ethernet1\n   description MLAG_PEER_spine1-DC1_Ethernet1\n\
    \   no shutdown\n   channel-group 1 mode active\n!\ninterface Ethernet2\n   description\
    \ LEAF1-DC1_Ethernet3\n   no shutdown\n   channel-group 2 mode active\n!\ninterface\
    \ Ethernet3\n   description LEAF2-DC1_Ethernet3\n   no shutdown\n   channel-group\
    \ 2 mode active\n!\ninterface Ethernet4\n   description LEAF3-DC1_Ethernet3\n\
    \   no shutdown\n   channel-group 4 mode active\n!\ninterface Ethernet5\n   description\
    \ LEAF4-DC1_Ethernet3\n   no shutdown\n   channel-group 4 mode active\n!\ninterface\
    \ Vlan4094\n   description MLAG_PEER\n   no shutdown\n   mtu 1500\n   no autostate\n\
    \   ip address 192.168.0.1/31\n!\nip routing\nno ip routing vrf MGMT\n!\nmlag\
    \ configuration\n   domain-id DC1_SPINES\n   local-interface Vlan4094\n   peer-address\
    \ 192.168.0.0\n   peer-link Port-Channel1\n   reload-delay mlag 300\n   reload-delay\
    \ non-mlag 330\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
  AVD_spine3-DC1: "!RANCID-CONTENT-TYPE: arista\n!\nvlan internal order ascending\
    \ range 1006 1199\n!\ntransceiver qsfp default-mode 4x10G\n!\nservice routing\
    \ protocols model multi-agent\n!\nhostname spine3-DC1\n!\nspanning-tree mode none\n\
    !\nno enable password\nno aaa root\n!\nvrf instance MGMT\n!\ninterface Ethernet2\n\
    \   description P2P_LINK_TO_LEAF1-DC1_Ethernet5\n   no shutdown\n   mtu 1500\n\
    \   no switchport\n   ip address 192.168.103.4/31\n!\ninterface Ethernet3\n  \
    \ description P2P_LINK_TO_LEAF2-DC1_Ethernet5\n   no shutdown\n   mtu 1500\n \
    \  no switchport\n   ip address 192.168.103.10/31\n!\ninterface Ethernet4\n  \
    \ description P2P_LINK_TO_LEAF3-DC1_Ethernet5\n   no shutdown\n   mtu 1500\n \
    \  no switchport\n   ip address 192.168.103.16/31\n!\ninterface Ethernet5\n  \
    \ description P2P_LINK_TO_LEAF4-DC1_Ethernet5\n   no shutdown\n   mtu 1500\n \
    \  no switchport\n   ip address 192.168.103.22/31\n!\ninterface Loopback0\n  \
    \ description EVPN_Overlay_Peering\n   no shutdown\n   ip address 192.168.101.103/32\n\
    !\nip routing\nno ip routing vrf MGMT\n!\nip prefix-list PL-LOOPBACKS-EVPN-OVERLAY\n\
    \   seq 10 permit 192.168.101.0/24 eq 32\n!\nroute-map RM-CONN-2-BGP permit 10\n\
    \   match ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY\n!\nrouter bfd\n  \
    \ multihop interval 300 min-rx 300 multiplier 3\n!\nrouter bgp 65001\n   router-id\
    \ 192.168.101.103\n   maximum-paths 4 ecmp 4\n   no bgp default ipv4-unicast\n\
    \   neighbor EVPN-OVERLAY-PEERS peer group\n   neighbor EVPN-OVERLAY-PEERS next-hop-unchanged\n\
    \   neighbor EVPN-OVERLAY-PEERS update-source Loopback0\n   neighbor EVPN-OVERLAY-PEERS\
    \ bfd\n   neighbor EVPN-OVERLAY-PEERS ebgp-multihop 3\n   neighbor EVPN-OVERLAY-PEERS\
    \ send-community\n   neighbor EVPN-OVERLAY-PEERS maximum-routes 0\n   neighbor\
    \ IPv4-UNDERLAY-PEERS peer group\n   neighbor IPv4-UNDERLAY-PEERS send-community\n\
    \   neighbor IPv4-UNDERLAY-PEERS maximum-routes 12000\n   neighbor 192.168.101.1\
    \ peer group EVPN-OVERLAY-PEERS\n   neighbor 192.168.101.1 remote-as 65101\n \
    \  neighbor 192.168.101.1 description leaf1-DC1\n   neighbor 192.168.101.2 peer\
    \ group EVPN-OVERLAY-PEERS\n   neighbor 192.168.101.2 remote-as 65101\n   neighbor\
    \ 192.168.101.2 description leaf2-DC1\n   neighbor 192.168.101.3 peer group EVPN-OVERLAY-PEERS\n\
    \   neighbor 192.168.101.3 remote-as 65103\n   neighbor 192.168.101.3 description\
    \ leaf3-DC1\n   neighbor 192.168.101.4 peer group EVPN-OVERLAY-PEERS\n   neighbor\
    \ 192.168.101.4 remote-as 65103\n   neighbor 192.168.101.4 description leaf4-DC1\n\
    \   neighbor 192.168.103.5 peer group IPv4-UNDERLAY-PEERS\n   neighbor 192.168.103.5\
    \ remote-as 65101\n   neighbor 192.168.103.5 description leaf1-DC1_Ethernet5\n\
    \   neighbor 192.168.103.11 peer group IPv4-UNDERLAY-PEERS\n   neighbor 192.168.103.11\
    \ remote-as 65101\n   neighbor 192.168.103.11 description leaf2-DC1_Ethernet5\n\
    \   neighbor 192.168.103.17 peer group IPv4-UNDERLAY-PEERS\n   neighbor 192.168.103.17\
    \ remote-as 65103\n   neighbor 192.168.103.17 description leaf3-DC1_Ethernet5\n\
    \   neighbor 192.168.103.23 peer group IPv4-UNDERLAY-PEERS\n   neighbor 192.168.103.23\
    \ remote-as 65103\n   neighbor 192.168.103.23 description leaf4-DC1_Ethernet5\n\
    \   redistribute connected route-map RM-CONN-2-BGP\n   !\n   address-family evpn\n\
    \      neighbor EVPN-OVERLAY-PEERS activate\n   !\n   address-family ipv4\n  \
    \    no neighbor EVPN-OVERLAY-PEERS activate\n      neighbor IPv4-UNDERLAY-PEERS\
    \ activate\n!\nmanagement api http-commands\n   protocol https\n   no shutdown\n\
    \   !\n   vrf MGMT\n      no shutdown\n!\nend\n"
CVP_TOPOLOGY:
  DC1:
    parent_container: FABRIC
  DC1_LEAFS:
    devices:
    - leaf1-DC1
    - leaf2-DC1
    - leaf3-DC1
    - leaf4-DC1
    parent_container: DC1
  DC1_SPINES:
    devices:
    - spine1-DC1
    - spine2-DC1
    parent_container: DC1
  FABRIC:
    parent_container: Tenant
changed: false
