configlet_list:
  MLAG_Left: "{{ lookup('file', '~/project/labfiles/Feb2024Level5/Ansible_CVP/configlets/MLAG_Left.txt') }}"
  MLAG_Right: "{{ lookup('file', '~/project/labfiles/Feb2024Level5/Ansible_CVP/configlets/MLAG_Right.txt') }}"

CVP_DEVICES:
  - fqdn: leaf1-DC1
    parentContainerName: Leaf-DC1
    configlets:
      - 'ATD-INFRA'
      - 'leaf1-DC1-BASE'
      - 'MLAG_Left'
  - fqdn: leaf2-DC1
    parentContainerName: Leaf-DC1
    configlets:
      - 'ATD-INFRA'
      - 'leaf2-DC1-BASE'
      - 'MLAG_Right'