---
servers:
  - name: host1-DC1
    adapters:
    - switch_ports:
      - Ethernet6
      - Ethernet7
      - Ethernet6
      - Ethernet7
      switches:
        - leaf1-DC1
        - leaf1-DC1
        - leaf2-DC1
        - leaf2-DC1
      vlans: 10
      mode: access
      spanning_tree_portfast: edge
      port_channel:
        description: connected to host1-DC1
        mode: active
  - name: host2-DC1
    adapters:
    - switch_ports:
      - Ethernet6
      - Ethernet7
      - Ethernet6
      - Ethernet7
      switches:
        - leaf3-DC1
        - leaf3-DC1
        - leaf4-DC1
        - leaf4-DC1
      vlans: 10
      mode: access
      spanning_tree_portfast: edge
      port_channel:
        description: connected to host2-DC1
        mode: active